import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '@/app/lib/AntdRegistry';
import { direction, getDictionary } from '@/app/i18n/dictionaries/dictionaries';
import { i18n } from '@/app/i18n/config';
import { LangProps } from '@/app/i18n/types';
import AntdConfigProvider from '@/app/lib/AntdConfigProvider';
import dayjs from 'dayjs';
import DayJSLocale from '@/app/lib/DayJSLocale';
import { consoleLogDev } from '@/app/utils/common';
import { TranslationProvider } from '../i18n/TranslationContext';

import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // TODO add hreflang tags https://localizely.com/blog/nextjs-i18n-tutorial/?tab=app-router#add-hreflang-tags-t0
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params: { lang },
}: React.PropsWithChildren<LangProps>) {
  consoleLogDev('update RootLayout');
  const dictionary = await getDictionary(lang);
  const dir = direction[lang];

  dayjs.locale(lang);

  return (
    <html lang={lang} dir={dir}>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <AntdConfigProvider locale={lang} dir={dir}>
            <TranslationProvider dictionary={dictionary} locale={lang}>
              {children}
            </TranslationProvider>
          </AntdConfigProvider>
        </StyledComponentsRegistry>
        <DayJSLocale />
      </body>
    </html>
  );
}
