import type { Metadata } from 'next';
import { dir } from 'i18next';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '@/app/lib/AntdRegistry';

import '../globals.css';
import { languages } from '@/app/i18n/settings';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// изучить
// export async function generateStaticParams() {
//   return languages.map((lng) => ({ lng }));
// }

export default function RootLayout({ children, params: { lang } }: { children: React.ReactNode }) {
  return (
    // изучить dir и i18next
    <html lang={lang} dir={dir(lang)}>
      <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
